import React, { useState, useEffect } from 'react';
import { Copy, CheckCircle, Smartphone, AlertCircle, X, Loader2 } from 'lucide-react';
import { Ticket } from '../types';

interface PaymentModalProps {
  ticket: Ticket;
  pixKey: string;
  onClose: () => void;
  onConfirm: () => void;
}

const PaymentModal: React.FC<PaymentModalProps> = ({ ticket, pixKey, onClose, onConfirm }) => {
  const [copied, setCopied] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);

  // Use the provided key or fallback
  const currentKey = pixKey || 'carlinhosvolpony@hotmail.com';

  // Construct a pseudo-valid PIX payload string for display/copy purposes
  // In a real app, this would be generated by a library (crc16, formatting)
  const pixCode = `00020126460014BR.GOV.BCB.PIX01${currentKey.length}${currentKey}52040000530398654042.005802BR5912RODADA DGRAU6008BRASILIA62070503***63041D3D`;

  const handleCopy = () => {
    navigator.clipboard.writeText(pixCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSimulatePayment = () => {
    setIsProcessing(true);
    setTimeout(() => {
      setIsProcessing(false);
      onConfirm();
    }, 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="bg-sports-card border border-slate-700 w-full max-w-md rounded-2xl p-6 shadow-2xl relative animate-in fade-in zoom-in duration-300">
        
        <button 
          onClick={onClose} 
          className="absolute top-4 right-4 text-slate-400 hover:text-white"
        >
          <X size={24} />
        </button>

        <div className="text-center mb-6">
          <div className="w-16 h-16 bg-sports-primary/20 rounded-full flex items-center justify-center mx-auto mb-4">
            <Smartphone className="text-sports-primary" size={32} />
          </div>
          <h2 className="text-2xl font-bold text-white mb-1">Finalizar Aposta</h2>
          <p className="text-slate-400 text-sm">Escaneie ou copie o código Pix abaixo</p>
        </div>

        <div className="bg-white p-4 rounded-xl mb-6 mx-auto w-48 h-48 flex items-center justify-center">
            {/* Simple CSS QR Code Pattern Simulation */}
            <div className="w-full h-full bg-[url('https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=ExamplePayment')] bg-contain bg-no-repeat bg-center opacity-90"></div>
        </div>

        <div className="mb-6">
            <div className="flex justify-between text-sm text-slate-300 mb-2">
                <span>Valor do Bilhete</span>
                <span className="font-bold text-white">R$ {ticket.price.toFixed(2).replace('.', ',')}</span>
            </div>
            <div className="flex justify-between text-sm text-slate-300 mb-4">
                <span>Prêmio Estimado</span>
                <span className="font-bold text-sports-accent">R$ {ticket.potentialWin.toLocaleString('pt-BR')}</span>
            </div>
            
            <div className="relative">
                <input 
                    readOnly 
                    value={pixCode} 
                    className="w-full bg-slate-900 border border-slate-700 text-slate-400 text-xs p-3 rounded-lg pr-12 font-mono truncate"
                />
                <button 
                    onClick={handleCopy}
                    className="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 hover:bg-slate-700 rounded-md text-sports-primary transition-colors"
                >
                    {copied ? <CheckCircle size={16} /> : <Copy size={16} />}
                </button>
            </div>
            <p className="text-[10px] text-slate-500 mt-2 text-center">Chave: {currentKey}</p>
            {copied && <p className="text-center text-green-400 text-xs mt-1">Código copiado!</p>}
        </div>

        <div className="bg-amber-900/30 border border-amber-700/50 p-3 rounded-lg mb-6 flex items-start gap-3">
            <AlertCircle className="text-amber-500 shrink-0 mt-0.5" size={16} />
            <p className="text-xs text-amber-200">
                Após o pagamento, seu bilhete será validado automaticamente para o próximo sorteio (12 jogos).
            </p>
        </div>

        <button 
            onClick={handleSimulatePayment}
            disabled={isProcessing}
            className="w-full bg-sports-primary hover:bg-green-500 text-white font-bold py-3.5 rounded-xl transition-all shadow-[0_4px_14px_0_rgba(16,185,129,0.39)] active:scale-95 flex items-center justify-center gap-2"
        >
            {isProcessing ? (
                <>
                    <Loader2 className="animate-spin" size={20} />
                    Processando...
                </>
            ) : (
                "Já realizei o pagamento"
            )}
        </button>
      </div>
    </div>
  );
};

export default PaymentModal;